version: "3"

services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb
      - ./influxdb/config/:/etc/influxdb/

  chronograf:
    image: chronograf:latest
    ports:
      - "8008:8008"
    links:
      - influxdb
      - kapacitor
    environment:
      - PORT=8008
    volumes:
      - ./chronograf/data/:/var/lib/chronograf/

  telegraf:
    image: telegraf:latest
    links:
      - influxdb
    volumes:
      - ./telegraf/:/etc/telegraf/

  kapacitor:
    image: kapacitor:latest
    ports:
      - "9092:9092"
    links:
      - influxdb
      - node
    volumes:
      - ./kapacitor/data/:/var/lib/kapacitor
      - ./kapacitor/config/:/etc/kapacitor/
      - ./kapacitor/tasks:/etc/kapacitor/load/tasks:ro

  node:
    build: ./node
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  jupyter:
    build: ./jupyter
    ports:
      - "8888:8888"
    links:
      - telegraf
    environment:
      - PASSWORD=password
    volumes:
      - ./jupyter/notebooks:/notebooks
